---

- name: Install package haproxy
  become: true
  yum:
    name: haproxy,libselinux-python
    state: latest

- selinux:
    state: disabled
  become: true

- name: Install configuration file haproxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg }}"
    owner: root
    group: root
    mode: '0644'
    setype: haproxy_config_t
  notify: restart haproxy
  become: true
