---

- name: Disbled Firewalld or Iptables
  become: true
  service:
    name: firewalld
    state: stopped
  
- name: Download Package HAProxy
  become: true
  get_url:
    url: "{{ haproxy_rpm_url }}/{{ haproxy_rpm_version }}"
    dest: /opt
    mode: 0440

- name: Install Package HAProxy
  become: true
  yum:
    name: "/opt/{{ haproxy_rpm_version }}"
    state: present

- name: Install packages
  become: true
  yum:
    name: libselinux-python,keepalived
    state: latest

- selinux:
    state: disabled
  become: true

- sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: true

- name: Apply configuration file haproxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg }}"
    owner: root
    group: root
    mode: '0644'
    setype: haproxy_cfg_t
  notify: restart haproxy
  become: true

- pam_limits:
    domain: haproxy
    limit_type: '-'
    limit_item: nofile
    value: 32000
  become: true

- name: Copy file pem certificate
  copy:
    src: "{{ cert_pem }}"
    dest: "{{ path_certs }}/{{ cert_pem }}"
    owner: root
    group: root
    mode: 0600
  become: true

- name: Install configuration file keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_conf }}"
    owner: root
    group: root
    mode: '0644'
    setype: keepalived_conf_t
  notify: restart keepalived
  become: true
